import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Alice } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/notifications/styles.css";
import "./globals.css";
import { Divider, MantineProvider } from "@mantine/core";
import { Header } from "@/components/Header/Header";
import { Notifications } from "@mantine/notifications";
import { InitGemstones } from "@/components/CommonComponents/InitGemstones";
import { Footer } from "@/components/CommonComponents/Footer";
import Head from "next/head";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const alice = Alice({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${alice.className}`}>
        <MantineProvider>
          <Notifications />
          <Header />
          <InitGemstones />
          {children}
          <Divider />
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
