import type { Metadata } from "next";
import { Montserrat, Alice } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/notifications/styles.css";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { ClientOnlyLayout } from "@/components/Layout/ClientOnlyLayout";
import { EmailSubscribeModal } from "@/components/CommonComponents/EmailSubscribeModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const alice = Alice({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${alice.className}`}>
        <MantineProvider>
          <Notifications />
          <ClientOnlyLayout>
            <EmailSubscribeModal />
            {children}
          </ClientOnlyLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
