export const US_STATES = [
  { value: "AL", label: "AL" },
  { value: "AK", label: "AK" },
  { value: "AZ", label: "AZ" },
  { value: "AR", label: "AR" },
  { value: "CA", label: "CA" },
  { value: "CO", label: "CO" },
  { value: "CT", label: "CT" },
  { value: "DE", label: "DE" },
  { value: "FL", label: "FL" },
  { value: "GA", label: "GA" },
  { value: "HI", label: "HI" },
  { value: "ID", label: "ID" },
  { value: "IL", label: "IL" },
  { value: "IN", label: "IN" },
  { value: "IA", label: "IA" },
  { value: "KS", label: "KS" },
  { value: "KY", label: "KY" },
  { value: "LA", label: "LA" },
  { value: "ME", label: "ME" },
  { value: "MD", label: "MD" },
  { value: "MA", label: "MA" },
  { value: "MI", label: "MI" },
  { value: "MN", label: "MN" },
  { value: "MS", label: "MS" },
  { value: "MO", label: "MO" },
  { value: "MT", label: "MT" },
  { value: "NE", label: "NE" },
  { value: "NV", label: "NV" },
  { value: "NH", label: "NH" },
  { value: "NJ", label: "NJ" },
  { value: "NM", label: "NM" },
  { value: "NY", label: "NY" },
  { value: "NC", label: "NC" },
  { value: "ND", label: "ND" },
  { value: "OH", label: "OH" },
  { value: "OK", label: "OK" },
  { value: "OR", label: "OR" },
  { value: "PA", label: "PA" },
  { value: "RI", label: "RI" },
  { value: "SC", label: "SC" },
  { value: "SD", label: "SD" },
  { value: "TN", label: "TN" },
  { value: "TX", label: "TX" },
  { value: "UT", label: "UT" },
  { value: "VT", label: "VT" },
  { value: "VA", label: "VA" },
  { value: "WA", label: "WA" },
  { value: "WV", label: "WV" },
  { value: "WI", label: "WI" },
  { value: "WY", label: "WY" },
];
export const AML_OPTIONS = [
  "Our company has established an anti-money laundering compliance program that meets the requirements of the USA PATRIOT Act and Bank Secrecy Act under the Interim Final Rule.",
  "Our company operates internationally and complies with anti-money laundering regulations set by our local authorities.",
  "Our company does not deal in precious metals, gemstones, or jewelry as defined by the Interim Final Rule of the USA PATRIOT Act, or is otherwise exempt.",
  "Our company is a retail business that is not required to comply with the USA PATRIOT Act because our purchases from non-dealers are under $50,000 annually.",
];

export const COUNTRY_OPTIONS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia, Plurinational State of",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela, Bolivarian Republic of",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
  "Other",
];

export const categoryOptions = [
  {
    label: "Bracelets",
    image: "/assets/bracelet-icon.png",
  },
  {
    label: "Necklaces",
    image: "/assets/necklace-icon.png",
  },
];

export const shapeOptions = [
  {
    label: "Round",
    image: "/assets/round-icon.png",
  },
];

export const braceletLengthOptions = [
  {
    label: "6.5 Inch",
  },
  {
    label: "7 Inch",
  },
  {
    label: "7.5 Inch",
  },
];
export const necklaceLengthOptions = [
  {
    label: "16 Inch",
  },
  {
    label: "18 Inch",
  },
  {
    label: "20 Inch",
  },
  {
    label: "22 Inch",
  },
];

export const stoneSizeOptions = [
  {
    value: "1.5 mm",
    label: "1.5 mm",
  },
  { value: "1.75 mm", label: "1.75 mm" },
  {
    value: "2 mm",
    label: "2 mm",
  },
  {
    value: "2.25 mm",
    label: "2.25 mm",
  },
  {
    value: "2.5 mm",
    label: "2.5 mm",
  },
  { value: "2.75 mm", label: "2.75 mm" },
  {
    value: "3 mm",
    label: "3 mm",
  },
  {
    value: "3.25 mm",
    label: "3.25 mm",
  },
  {
    value: "3.5 mm",
    label: "3.5 mm",
  },
  {
    value: "3.75 mm",
    label: "3.75 mm",
  },
  {
    value: "4 mm",
    label: "4 mm",
  },
];
export const gemstoneOptions = [
  {
    label: "Alexandrite",
    value: "Alexandrite",
    image: "/assets/sapphire.png",
  },
  { label: "Amethyst", value: "Amethyst", image: "/assets/amethyst.png" },
  { label: "Aquamarine", value: "Aquamarine", image: "/assets/aquamarine.png" },
  { label: "Citrine", value: "Citrine", image: "/assets/citrine.png" },
  { label: "Emerald", value: "Emerald", image: "/assets/emerald.png" },
  { label: "Morganite", value: "Morganite", image: "/assets/morganite.png" },
  { label: "Peridot", value: "Peridot", image: "/assets/peridot.png" },
  { label: "Ruby", value: "Ruby", image: "/assets/ruby.png" },
  { label: "Sapphire", value: "Sapphire", image: "/assets/sapphire.png" },
  { label: "Tanzanite", value: "Tanzanite", image: "/assets/tanzanite.png" },
  { label: "Tsavorite", value: "Tsavorite", image: "/assets/tsavorite.png" },
  {
    label: "Lab Diamond",
    value: "Lab Diamond",
    image: "/assets/lab-diamond.png",
  },
  {
    label: "Black Diamond",
    value: "Black Diamond",
    image: "/assets/black-diamond.png",
  },
];

export const colorOptions: any = {
  Sapphire: [
    { label: "Blue", value: "blue", color: "#1E40AF" },
    { label: "Yellow", value: "yellow", color: "#FACC15" },
    { label: "Pink", value: "pink", color: "#EC4899" },
    { label: "Green", value: "green", color: "#22C55E" },
    { label: "Orange", value: "orange", color: "#F97316" },
    { label: "Multi color", value: "multi-color", color: "#D946EF" },
  ],
  Ruby: [
    { label: "Pinkish Red", value: "pinkish-red", color: "#E0115F" },
    { label: "Piegion Blood", value: "piegion-blood", color: "#9B111E" },
    { label: "Medium Red", value: "medium-red", color: "#AA4069" },
    { label: "Deep Red", value: "deep-red", color: "#850101" },
  ],
  Tsavorite: [{ label: "Green", value: "green", color: "#059669" }],
};

export const patternOptions = [
  {
    value: "straight-pattern",
    label: "Straight Pattern",
    description: "A clean, consistent line of one gemstone color throughout.",
    image: "/assets/straight-img.png",
  },
  {
    value: "ombre-pattern",
    label: "Ombre Pattern",
    description: "A gradient-style blend from one gemstone color to another.",
    image: "/assets/ombre-img.png",
  },
  {
    value: "custom-details",
    label: "Give Your Pattern",
  },
];

export const quickNavigationData = [
  {
    value: "education",
    label: "Education",
    children: [
      {
        label: "Gemstone Education",
        href: "/customer-support/gemstone-education",
      },
    ],
  },
  {
    value: "get-to-know-us",
    label: "Get to Know Us",
    children: [
      {
        label: "About Us",
        href: "/customer-support/about-us",
      },
    ],
  },
  {
    value: "customer-center",
    label: "Customer Center",
    children: [
      {
        label: "Contact Us",
        href: "/customer-support/contact-us",
      },
      {
        label: "Frequently Asked Questions",
        href: "/customer-support/faqs",
      },
    ],
  },
  {
    value: "our-policies",
    label: "Our Policies",
    children: [
      {
        label: "Store Policy",
        href: "/customer-support/store-policy",
      },
      {
        label: "Return Policy",
        href: "/customer-support/return-policy",
      },
      {
        label: "Shipping Policy",
        href: "/customer-support/shipping-policy",
      },
    ],
  },
  {
    value: "site-map",
    label: "Site Map",
    children: [
      {
        label: "Site Map",
        href: "/customer-support/sitemap",
      },
    ],
  },
];
