export const STONE_COLORS: any = {
  Ruby: "Red",
  Emerald: "Green",
  "Pink Sapphire": "Pink",
  "Blue Sapphire": "Blue",
};
export type BigThree = "sapphire" | "emerald" | "ruby";

export interface GemLocation {
  gem: BigThree;
  country: string;
  locality: string;
  color_profile: string;
  season_open: string;
  coords: [number, number];
  mining_info: string;
  quality_notes: string;
}

export const GEM_LOCATIONS: GemLocation[] = [
  // SAPPHIRES (10 locations)
  {
    gem: "sapphire",
    country: "Sri Lanka",
    locality: "Ratnapura",
    color_profile: "Wide palette: royal to pastel blues, pink, yellow, white",
    season_open: "Year-round; monsoon May–September may disrupt operations",
    coords: [6.6828, 80.3992],
    mining_info:
      "Alluvial mining in gem gravels, traditional pit mining methods",
    quality_notes: "Famous for cornflower blue sapphires and rare padparadscha",
  },
  {
    gem: "sapphire",
    country: "Myanmar",
    locality: "Mogok",
    color_profile: "Royal blue, vivid blues, some pink and yellow",
    season_open: "Year-round with peak season October-March",
    coords: [22.918, 96.509],
    mining_info: "Hard rock mining in marble deposits",
    quality_notes: "Produces some of the world's finest blue sapphires",
  },
  {
    gem: "sapphire",
    country: "Madagascar",
    locality: "Ilakaka",
    color_profile: "Blue, pink, yellow, orange, white, color-change",
    season_open: "Year-round, rainy season December-March",
    coords: [-22.7, 45.3],
    mining_info: "Alluvial deposits, artisanal mining predominant",
    quality_notes: "Major source since 1998, wide variety of colors",
  },
  {
    gem: "sapphire",
    country: "Australia",
    locality: "New England",
    color_profile: "Deep blue, some parti-colored and yellow",
    season_open: "Year-round operation",
    coords: [-30.5, 151.5],
    mining_info: "Basalt-hosted deposits, mechanized mining",
    quality_notes: "Known for deep, dark blue sapphires",
  },
  {
    gem: "sapphire",
    country: "Thailand",
    locality: "Kanchanaburi",
    color_profile: "Blue, yellow, some color-change",
    season_open: "Year-round, reduced activity during monsoons",
    coords: [14.0, 99.5],
    mining_info: "Alluvial and hard rock mining",
    quality_notes: "Important cutting and trading center",
  },
  {
    gem: "sapphire",
    country: "Cambodia",
    locality: "Pailin",
    color_profile: "Blue, some pink and yellow varieties",
    season_open: "Dry season October-May preferred",
    coords: [12.85, 102.6],
    mining_info: "Alluvial mining in ancient river deposits",
    quality_notes: "High-quality blue sapphires, limited production",
  },
  {
    gem: "sapphire",
    country: "Tanzania",
    locality: "Songea",
    color_profile: "Blue, pink, yellow, orange, some color-change",
    season_open: "Year-round, peak dry season June-October",
    coords: [-10.68, 35.65],
    mining_info: "Alluvial and eluvial deposits",
    quality_notes: "Source of fine color-change sapphires",
  },
  {
    gem: "sapphire",
    country: "Kashmir",
    locality: "Paddar Valley",
    color_profile: "Legendary cornflower blue with silk",
    season_open: "Limited seasonal access, June-September",
    coords: [33.2, 76.3],
    mining_info: "High-altitude deposits, extremely limited mining",
    quality_notes: "Most prized sapphires in the world, very rare",
  },
  {
    gem: "sapphire",
    country: "United States",
    locality: "Yogo Gulch, Montana",
    color_profile: "Cornflower blue, exceptional clarity",
    season_open: "May-October due to harsh winters",
    coords: [47.0, -110.5],
    mining_info: "Igneous intrusion, limited commercial mining",
    quality_notes: "Naturally untreated, exceptional clarity",
  },
  {
    gem: "sapphire",
    country: "Vietnam",
    locality: "Luc Yen",
    color_profile: "Blue, pink, some color-change varieties",
    season_open: "Year-round with seasonal variations",
    coords: [22.0, 104.5],
    mining_info: "Marble-hosted deposits, artisanal mining",
    quality_notes: "Emerging source of fine-quality sapphires",
  },

  // EMERALDS (5 locations)
  {
    gem: "emerald",
    country: "Colombia",
    locality: "Muzo",
    color_profile: "Deep bluish green, exceptional saturation",
    season_open: "Year-round operation",
    coords: [5.5353, -74.1074],
    mining_info: "Sedimentary rock deposits, underground mining",
    quality_notes: "World's most prized emeralds, distinctive inclusions",
  },
  {
    gem: "emerald",
    country: "Zambia",
    locality: "Kagem Mine",
    color_profile: "Rich bluish-green, slightly darker than Colombian",
    season_open: "Year-round operation",
    coords: [-13.0833, 28.05],
    mining_info: "Open-pit and underground mining in schist deposits",
    quality_notes: "World's largest emerald mine, consistent quality",
  },
  {
    gem: "emerald",
    country: "Brazil",
    locality: "Itabira",
    color_profile: "Light to medium green, some with blue undertones",
    season_open: "Year-round, rainy season December-March",
    coords: [-19.6167, -43.2333],
    mining_info: "Pegmatite deposits, varied mining methods",
    quality_notes: "Source of large, clean emeralds",
  },
  {
    gem: "emerald",
    country: "Afghanistan",
    locality: "Panjshir Valley",
    color_profile: "Medium to dark green, good saturation",
    season_open: "Limited due to security concerns",
    coords: [35.3, 69.5],
    mining_info: "High-altitude deposits, traditional methods",
    quality_notes: "Historic source, production currently limited",
  },
  {
    gem: "emerald",
    country: "Ethiopia",
    locality: "Shakiso",
    color_profile: "Light to medium green, often eye-clean",
    season_open: "Year-round operation",
    coords: [5.75, 38.92],
    mining_info: "Relatively new discovery, modern mining techniques",
    quality_notes: "Emerging source with commercial potential",
  },

  // RUBIES (5 locations)
  {
    gem: "ruby",
    country: "Myanmar",
    locality: "Mogok Valley",
    color_profile: "Pigeon's-blood red, exceptional fluorescence",
    season_open: "Year-round with peak October-March",
    coords: [22.918, 96.509],
    mining_info: "Marble-hosted deposits, traditional and modern methods",
    quality_notes: "World's finest rubies, legendary pigeon's-blood color",
  },
  {
    gem: "ruby",
    country: "Mozambique",
    locality: "Montepuez",
    color_profile: "Vivid reds, some with pink undertones",
    season_open: "Year-round; rains December-March may slow operations",
    coords: [-13.1333, 39.0833],
    mining_info: "Large-scale mechanized mining operation",
    quality_notes: "Major new source since 2009, large production",
  },
  {
    gem: "ruby",
    country: "Thailand",
    locality: "Chanthaburi",
    color_profile: "Dark red to purplish red",
    season_open: "Year-round operation",
    coords: [12.6103, 102.1035],
    mining_info: "Basalt-hosted deposits, alluvial mining",
    quality_notes: "Important for ruby treatment and trading",
  },
  {
    gem: "ruby",
    country: "Madagascar",
    locality: "Andilamena",
    color_profile: "Pink to red, some exceptional red specimens",
    season_open: "Dry season April-November preferred",
    coords: [-17.0, 48.5],
    mining_info: "Alluvial and hard rock deposits",
    quality_notes: "Produces both rubies and pink sapphires",
  },
  {
    gem: "ruby",
    country: "Tanzania",
    locality: "Winza",
    color_profile: "Pinkish red to red, good transparency",
    season_open: "Year-round with seasonal access variations",
    coords: [-6.5, 35.8],
    mining_info: "Small-scale artisanal mining",
    quality_notes: "Relatively new source, limited but fine quality",
  },
];

export const US_STATES = [
  { value: "AL", label: "AL" },
  { value: "AK", label: "AK" },
  { value: "AZ", label: "AZ" },
  { value: "AR", label: "AR" },
  { value: "CA", label: "CA" },
  { value: "CO", label: "CO" },
  { value: "CT", label: "CT" },
  { value: "DE", label: "DE" },
  { value: "FL", label: "FL" },
  { value: "GA", label: "GA" },
  { value: "HI", label: "HI" },
  { value: "ID", label: "ID" },
  { value: "IL", label: "IL" },
  { value: "IN", label: "IN" },
  { value: "IA", label: "IA" },
  { value: "KS", label: "KS" },
  { value: "KY", label: "KY" },
  { value: "LA", label: "LA" },
  { value: "ME", label: "ME" },
  { value: "MD", label: "MD" },
  { value: "MA", label: "MA" },
  { value: "MI", label: "MI" },
  { value: "MN", label: "MN" },
  { value: "MS", label: "MS" },
  { value: "MO", label: "MO" },
  { value: "MT", label: "MT" },
  { value: "NE", label: "NE" },
  { value: "NV", label: "NV" },
  { value: "NH", label: "NH" },
  { value: "NJ", label: "NJ" },
  { value: "NM", label: "NM" },
  { value: "NY", label: "NY" },
  { value: "NC", label: "NC" },
  { value: "ND", label: "ND" },
  { value: "OH", label: "OH" },
  { value: "OK", label: "OK" },
  { value: "OR", label: "OR" },
  { value: "PA", label: "PA" },
  { value: "RI", label: "RI" },
  { value: "SC", label: "SC" },
  { value: "SD", label: "SD" },
  { value: "TN", label: "TN" },
  { value: "TX", label: "TX" },
  { value: "UT", label: "UT" },
  { value: "VT", label: "VT" },
  { value: "VA", label: "VA" },
  { value: "WA", label: "WA" },
  { value: "WV", label: "WV" },
  { value: "WI", label: "WI" },
  { value: "WY", label: "WY" },
];
export const AML_OPTIONS = [
  "Our company has established an anti-money laundering compliance program that meets the requirements of the USA PATRIOT Act and Bank Secrecy Act under the Interim Final Rule.",
  "Our company operates internationally and complies with anti-money laundering regulations set by our local authorities.",
  "Our company does not deal in precious metals, gemstones, or jewelry as defined by the Interim Final Rule of the USA PATRIOT Act, or is otherwise exempt.",
  "Our company is a retail business that is not required to comply with the USA PATRIOT Act because our purchases from non-dealers are under $50,000 annually.",
];

export const COUNTRY_OPTIONS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia, Plurinational State of",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela, Bolivarian Republic of",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
  "Other",
];

export const categoryOptions = [
  {
    label: "Bracelets",
    image: "/assets/bracelet-icon.png",
  },
  {
    label: "Necklaces",
    image: "/assets/necklace-icon.png",
  },
];

export const shapeOptions = [
  {
    label: "Round",
    image: "/assets/round-icon.png",
  },
];

export const braceletLengthOptions = [
  {
    label: "6.5 Inch",
  },
  {
    label: "7 Inch",
  },
  {
    label: "7.5 Inch",
  },
];
export const necklaceLengthOptions = [
  {
    label: "16 Inch",
  },
  {
    label: "18 Inch",
  },
  {
    label: "20 Inch",
  },
  {
    label: "22 Inch",
  },
];

export const stoneSizeOptions = [
  {
    value: "1.5 mm",
    label: "1.5 mm",
  },
  { value: "1.75 mm", label: "1.75 mm" },
  {
    value: "2 mm",
    label: "2 mm",
  },
  {
    value: "2.25 mm",
    label: "2.25 mm",
  },
  {
    value: "2.5 mm",
    label: "2.5 mm",
  },
  { value: "2.75 mm", label: "2.75 mm" },
  {
    value: "3 mm",
    label: "3 mm",
  },
  {
    value: "3.25 mm",
    label: "3.25 mm",
  },
  {
    value: "3.5 mm",
    label: "3.5 mm",
  },
  {
    value: "3.75 mm",
    label: "3.75 mm",
  },
  {
    value: "4 mm",
    label: "4 mm",
  },
];

export const RingTypes = [
  {
    label: "Solitaire",
    value: "Solitaire",
  },
  {
    label: "Bezel",
    value: "Bezel",
  },
  {
    label: "Three Stone",
    value: "Three Stone",
  },
  {
    label: "Band",
    value: "Band",
  },
];

export const EarringTypes = [
  {
    label: "Gold",
    value: "Gold",
  },
  {
    label: "Silver",
    value: "Silver",
  },
];

export const JewelryGemstones = [
  {
    label: "Ruby",
    value: "Ruby",
  },
  {
    label: "Emerald",
    value: "Emerald",
  },
  {
    label: "Pink Sapphire",
    value: "Pink Sapphire",
  },
  {
    label: "Blue Sapphire",
    value: "Blue Sapphire",
  },
];
export const gemstoneOptions = [
  {
    label: "Alexandrite",
    value: "Alexandrite",
    image: "/assets/sapphire.png",
    link: "/alexandrite",
  },
  {
    label: "Amethyst",
    value: "Amethyst",
    image: "/assets/amethyst.png",
    link: "/amethyst",
  },
  {
    label: "Aquamarine",
    value: "Aquamarine",
    image: "/assets/aquamarine.png",
    link: "/aquamarine",
  },
  {
    label: "Citrine",
    value: "Citrine",
    image: "/assets/citrine.png",
    link: "/citrine",
  },
  {
    label: "Emerald",
    value: "Emerald",
    image: "/assets/emerald.png",
    link: "/emerald",
  },
  {
    label: "Morganite",
    value: "Morganite",
    image: "/assets/morganite.png",
    link: "/morganite",
  },
  {
    label: "Paraiba Tourmaline",
    value: "Paraiba Tourmaline",
    image: "/assets/pariba.png",
    link: "/paraiba-tourmaline",
  },
  {
    label: "Peridot",
    value: "Peridot",
    image: "/assets/peridot.png",
    link: "/peridot",
  },
  {
    label: "Ruby",
    value: "Ruby",
    image: "/assets/ruby.png",
    link: "/ruby",
  },
  {
    label: "Sapphire",
    value: "Sapphire",
    image: "/assets/sapphire.png",
    link: "/sapphire",
  },
  {
    label: "Tanzanite",
    value: "Tanzanite",
    image: "/assets/tanzanite.png",
    link: "/tanzanite",
  },
];

export const colorOptions: any = {
  Sapphire: [
    { label: "Blue", value: "blue", color: "#1E40AF" },
    { label: "Yellow", value: "yellow", color: "#FACC15" },
    { label: "Pink", value: "pink", color: "#EC4899" },
    { label: "Green", value: "green", color: "#22C55E" },
    { label: "Orange", value: "orange", color: "#F97316" },
    { label: "Multi color", value: "multi-color", color: "#D946EF" },
  ],
  Ruby: [
    { label: "Pinkish Red", value: "pinkish-red", color: "#E0115F" },
    { label: "Piegion Blood", value: "piegion-blood", color: "#9B111E" },
    { label: "Medium Red", value: "medium-red", color: "#AA4069" },
    { label: "Deep Red", value: "deep-red", color: "#850101" },
  ],
  Tsavorite: [{ label: "Green", value: "green", color: "#059669" }],
};

export const patternOptions = [
  {
    value: "straight-pattern",
    label: "Straight Pattern",
    description: "A clean, consistent line of one gemstone color throughout.",
    image: "/assets/straight-img.png",
  },
  {
    value: "ombre-pattern",
    label: "Ombre Pattern",
    description: "A gradient-style blend from one gemstone color to another.",
    image: "/assets/ombre-img.png",
  },
  {
    value: "custom-details",
    label: "Give Your Pattern",
  },
];

export const FreeSizeGemstonesList = [
  {
    label: "Sapphire",
    value: "Sapphire",
    image: "/assets/freesizesapphire.png",
    link: "/free-size-gemstones/sapphire",
  },
  {
    label: "Ruby",
    value: "Ruby",
    image: "/assets/freesizeruby.png",
    link: "/free-size-gemstones/ruby",
  },

  {
    label: "Emerald",
    value: "Emerald",
    image: "/assets/freesizeemerald.png",
    link: "/free-size-gemstones/emerald",
  },
];

export const quickNavigationData = [
  {
    value: "education",
    label: "Education",
    children: [
      {
        label: "Gemstone Education",
        href: "/customer-support/education?activeStone=alexandrite",
      },
    ],
  },
  {
    value: "get-to-know-us",
    label: "Get to Know Us",
    children: [
      {
        label: "About Us",
        href: "/customer-support/about-us",
      },
    ],
  },
  {
    value: "customer-center",
    label: "Customer Center",
    children: [
      {
        label: "Contact Us",
        href: "/customer-support/contact-us",
      },
      {
        label: "FAQs",
        href: "/customer-support/faqs",
      },
    ],
  },
  {
    value: "our-policies",
    label: "Our Policies",
    children: [
      {
        label: "Store Policy",
        href: "/customer-support/store-policy",
      },
      // {
      //   label: "Return Policy",
      //   href: "/customer-support/return-policy",
      // },
    ],
  },
];

export const shopByColorOptions = [
  {
    name: "Ruby Red",
    image: "/assets/ruby-red-by-color.png",
    color: "red",
  },
  {
    name: "Pink Sapphire",

    image: "/assets/pink-sapphire-by-color.png",
    color: "pink",
  },
  {
    name: "Tanzanite",

    image: "/assets/tanzanite-color.png",
    color: "purple",
  },
  {
    name: "Blue Sapphire",

    image: "/assets/blue-sapphire-by-color.png",
    color: "blue",
  },
  {
    name: "Emerald Green",

    image: "/assets/green-emerald-by-color.png",
    color: "green",
  },
  {
    name: "Yellow Sapphire",

    image: "/assets/yellow-sapphire-color.png",
    color: "yellow",
  },
];

export const ShapeFilterList = [
  {
    label: "Round",
    image: "/assets/round.svg",
  },
  {
    label: "Oval",
    image: "/assets/oval.svg",
  },
  {
    label: "Princess Cut",
    image: "/assets/princesscut.svg",
  },
  {
    label: "Emerald Cut",
    image: "/assets/emerald.svg",
  },
  {
    label: "Pear",
    image: "/assets/pear.svg",
  },
  {
    label: "Marquise",
    image: "/assets/marquise.svg",
  },
  {
    label: "Cushion",
    image: "/assets/cushion.svg",
  },
  {
    label: "Trillion",
    image: "/assets/trillion.svg",
  },
  {
    label: "Heart",
    image: "/assets/heart.svg",
  },
  {
    label: "Straight Baguette",
    image: "/assets/baguette.svg",
  },
];

export const SizeFilterList = {
  Round: [
    "0.8 - 1",
    "1.1 - 1.5",
    "1.6 - 2",
    "2.25 - 3",
    "3.25 - 4.5",
    "5 - 6",
    "6.5 - 8",
    "9 - 11",
    "12 - 13",
    "14 - 16",
  ],
  Others: [
    "2x2",
    "2.25x2.25",
    "2.5x2.5",
    "2.75x2.75",
    "3x1.5",
    "3x1.75",
    "3x2",
    "3x3",
    "3.5x1.5",
    "3.5x1.75",
    "3.5x2",
    "3.5x3.5",
    "4x1.5",
    "4x2",
    "4x3",
    "4x4",
    "4.5x2",
    "4.5x2.5",
    "4.5x4.5",
    "5x2",
    "5x2.5",
    "5x3",
    "5x5",
    "5.5x5.5",
    "6x3",
    "6x4",
    "6x6",
    "6.5x6.5",
    "7x3.5",
    "7x5",
    "7x7",
    "8x4",
    "8x5",
    "8x6",
    "8x8",
    "9x4.5",
    "9x6",
    "9x7",
    "9x9",
    "10x5",
    "10x7",
    "10x8",
    "10x10",
    "11x9",
    "11x11",
    "12x7",
    "12x8",
    "12x10",
    "12x12",
    "13x9",
    "13x13",
    "14x9",
    "14x10",
    "14x12",
    "14x14",
    "15x10",
    "15x13",
    "16x12",
    "16x13",
    "16x16",
    "17x10",
    "17x14",
    "18x10",
    "18x11",
    "18x13",
    "18x18",
    "19x11",
    "19x19",
    "20x11",
  ],
};

export const JewelryList = [
  { link: "/jewelry/rings", label: "Rings" },
  { link: "/jewelry/earrings", label: "Earrings" },
  { link: "/jewelry/necklaces", label: "Necklaces" },
  { link: "/jewelry/bracelets", label: "Bracelets" },
  { link: "/custom-jewelry", label: "Build Custom Jewelry" },
];

export const links = [
  { link: "/", label: "Home" },
  {
    link: "/loose-gemstones",
    label: "Gemstones",
    links: gemstoneOptions,
  },

  {
    label: "Jewelry",
    links: JewelryList,
  },
  { link: "/precious-beads", label: "Precious Beads" },

  { link: "/create-colorstone-layout", label: "Colorstone Layouts" },
  {
    label: "More",
    links: [
      {
        link: "/customer-support/education?activeStone=alexandrite",
        label: "Gemstones Education",
      },
      {
        link: "/customer-support/gemstones-by-locations",
        label: "Gemstones By Location",
      },
      { link: "/customer-support/about-us", label: "About B. V. Gems" },
      { link: "/customer-support/store-policy", label: "Store Policy" },
      { link: "/customer-support/faqs", label: "FAQ" },
      { link: "/customer-support/contact-us", label: "Contact Us" },
    ],
  },
];
export const mobileLinks = [
  { link: "/", label: "Home" },
  {
    link: "/loose-gemstones",
    label: "Calibrated Gemstones",
    links: gemstoneOptions,
  },
  { link: "/free-size-gemstones", label: "Free Size Gemstones" },

  {
    label: "Jewelry",
    links: JewelryList,
  },
  { link: "/precious-beads", label: "Precious Beads" },

  { link: "/create-colorstone-layout", label: "Colorstone Layouts" },
  {
    label: "More",
    links: [
      {
        link: "/customer-support/education?activeStone=alexandrite",
        label: "Gemstones Education",
      },
      {
        link: "/customer-support/gemstones-by-locations",
        label: "Gemstones By Location",
      },
      { link: "/customer-support/about-us", label: "About B. V. Gems" },
      { link: "/customer-support/store-policy", label: "Store Policy" },
      { link: "/customer-support/faqs", label: "FAQ" },
      { link: "/customer-support/contact-us", label: "Contact Us" },
    ],
  },
];

export const GoldColorData = [
  { value: "Rose Gold", color: "#b76e79" },
  { value: "White Gold", color: "#e5e4e2" },
  { value: "Yellow Gold", color: "#ffd700" },
];

export const SapphireLooseGemstoneColorOptions = [
  { value: "Blue", color: "#1E40AF" },
  { value: "Yellow", color: "#FACC15" },
  { value: "Pink", color: "#EC4899" },
  { value: "Green", color: "#22C55E" },
  { value: "Orange", color: "#F97316" },
  // { value: "Black", color: "#000000" },
  // { value: "White", color: "#808080" },
  // { value: "Red", color: "#FF0000" },
  { value: "Purple", color: "#800080" },
];

export const FreeSizeOrigins: any = {
  Emerald: ["Columbia", "Zambia"],
  Ruby: ["Mozambique", "Burma"],
  Sapphire: ["Australia", "Madagascar", "Ceylon", "Thai"],
};

export const IndustryAffiliationOptions = [
  {
    logo: "/assets/agta-logo.png",
    link: "https://agta.org/",
  },
  {
    logo: "/assets/jbt-logo.png",
    link: "https://www.jewelersboard.com/",
  },
  {
    logo: "/assets/polygon-logo.png",
    link: "https://www.polygon.net/jwl/public/colored-stones/buy-colored-stones-en.jsp",
  },
  {
    logo: "/assets/idca-logo.png",
    link: "https://idcany.org/",
  },
];

export const GemstoneType = [
  {
    label: "Natural",
  },
  {
    label: "Lab Grown",
  },
];
