# .github/workflows/abandoned-cart.yml

name: Abandoned Cart Cron

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  abandoned-cart:
    runs-on: ubuntu-latest

    steps:
      - name: Call Abandoned Cart API
        run: |
          response=$(curl -L -s -o /dev/null -w "%{http_code}" \
            -X GET https://www.bvgems.com/api/cron/abandoned-cart \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}")

          echo "Response code: $response"

          if [ "$response" != "200" ]; then
            echo "Cron job failed with status $response"
            exit 1
          fi
